DROP DATABASE IF EXISTS RENOMAXACCOUNTINGDB;
CREATE DATABASE RENOMAXACCOUNTINGDB;
USE RENOMAXACCOUNTINGDB;

DROP USER IF EXISTS TheUser@localhost;
CREATE USER TheUser@'localhost' IDENTIFIED BY 'mainPassword';
GRANT ALL ON RENOMAXACCOUNTINGDB.* TO TheUser@'localhost';

FLUSH PRIVELEGES;
