USE RENOMAXACCOUNTINGDB;

DROP TABLE IF EXISTS EXPENSES;
DROP TABLE IF EXISTS INVOICES;
DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS SUPPLIERS;
DROP TABLE IF EXISTS MAINDESCRIPTION;
DROP TABLE IF EXISTS SUBDESCRIPTION;

CREATE TABLE SUPPLIERS(
    SUPPLIERID INT AUTO_INCREMENT PRIMARY KEY,
    SUPPLIERNAME VARCHAR(64) NOT NULL
);

CREATE TABLE MAINDESCRIPTION(
    MAINDESCRIPTIONID INT AUTO_INCREMENT PRIMARY KEY,
    MAINDESCRIPTIONNAME VARCHAR(128) NOT NULL
);

CREATE TABLE SUBDESCRIPTION(
    SUBDESCRIPTIONID INT AUTO_INCREMENT PRIMARY KEY,
    SUBDESCRIPTIONNAME VARCHAR(128) NOT NULL
);

CREATE TABLE EXPENSES(
    EXPENSEID INT AUTO_INCREMENT PRIMARY KEY,
    DATETIME DATE NOT NULL,
    SUPPLIERID INT NOT NULL,
    MAINDESCRIPTIONID INT,
    SUBDESCRIPTIONID INT,
    SUBTOTAL DECIMAL(6,2) NOT NULL,
    GST DECIMAL(6,3),
    QST DECIMAL(6,3),
    TOTAL DECIMAL(6,2) NOT NULL,
    FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIERS (SUPPLIERID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MAINDESCRIPTIONID) REFERENCES MAINDESCRIPTION (MAINDESCRIPTIONID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (SUBDESCRIPTIONID) REFERENCES SUBDESCRIPTION (SUBDESCRIPTIONID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CLIENTS(
    CLIENTID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTNAME VARCHAR(64) NOT NULL,
    STREET VARCHAR(64),
    CITY VARCHAR(64),
    PROVINCE VARCHAR(64),
    POSTALCODE VARCHAR(64),
    HOMEPHONE VARCHAR(64),
    CELLPHONE VARCHAR(64),
    EMAIL VARCHAR(64)
);

CREATE TABLE INVOICES(
    INVOICEID INT AUTO_INCREMENT PRIMARY KEY,
    INVOICENUMBER INT NOT NULL,
    INVOICEDATE DATE NOT NULL,
    CLIENTID INT NOT NULL,
    SUBTOTAL DECIMAL(6,2) NOT NULL,
    GST DECIMAL(6,3),
    QST DECIMAL(6,3),
    TOTAL DECIMAL(6,2) NOT NULL,
    INVOICESENT BOOLEAN,
    FOREIGN KEY (CLIENTID) REFERENCES CLIENTS (CLIENTID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO SUPPLIERS(SUPPLIERID, SUPPLIERNAME) 
    VALUES(1, "Ceramique Royale");

INSERT INTO MAINDESCRIPTION(MAINDESCRIPTIONID, MAINDESCRIPTIONNAME)
    VALUES(1, "Material");

INSERT INTO SUBDESCRIPTION(SUBDESCRIPTIONID, SUBDESCRIPTIONNAME)
    VALUES(1, "Tools");

INSERT INTO CLIENTS(CLIENTID, CLIENTNAME, STREET, CITY, PROVINCE, POSTALCODE, HOMEPHONE, CELLPHONE, EMAIL)
    VALUES(1, "Doctor Miller", "tempst", "tempcty", "tempprov", "temppcode", "temphphone", "tempcphone", "tempemail");